version: "3"
# volumes:
#    pgdata:
#      driver: "local"
services:
  postgres:
    build: .
    container_name: "postgres12"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "passpass"
    command: 'postgres -c config_file="/etc/postgresql.conf"'
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
      - "./conf/postgresql.conf:/etc/postgresql.conf"
      - "./sql:/docker-entrypoint-initdb.d"
